### ISSUE TITLE
Panic when running the marking example

### ISSUE THREAD

**Issue by linkmauve** [nicopap/ui-navigation#21]
Here is the backtrace I get when I try to run this example, on master:
```rust
% time RUST_BACKTRACE=1 cargo run --release --example=marking
    Finished release [optimized] target(s) in 0.16s
     Running `target/release/examples/marking`
2022-04-28T07:36:04.300799Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1.25
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

2022-04-28T07:36:04.328761Z  INFO bevy_render::renderer: AdapterInfo { name: "Intel(R) UHD Graphics 620 (KBL GT2)", vendor: 32902, device: 22807, device_type: IntegratedGpu, backend: Vulkan }
thread 'main' panicked at 'error[B0001]: Query<(bevy_ecs::entity::Entity, &mut bevy_ui_navigation::resolve::TreeMenu), bevy_ecs::query::filter::Without<bevy_ui_navigation::resolve::Focusable>> in system bevy_ui_navigation::marker::mark_new_menus<marking::LeftColMenu> accesses component(s) bevy_ui_navigation::resolve::TreeMenu in a way that conflicts with a previous system parameter. Consider using `Without<T>` to create disjoint Queries or merging conflicting Queries into a `ParamSet`.', /home/linkmauve/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.7.0/src/system/system_param.rs:173:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8bf93e9b6791acee3a594ed202fdfe45ad9952b5/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/8bf93e9b6791acee3a594ed202fdfe45ad9952b5/library/core/src/panicking.rs:142:14
   2: bevy_ecs::system::system_param::assert_component_access_compatibility
   3: <bevy_ecs::query::state::QueryState<Q,F> as bevy_ecs::system::system_param::SystemParamState>::init
   4: <bevy_ui_navigation::resolve::NavQueriesState<TSystemParamState> as bevy_ecs::system::system_param::SystemParamState>::init
   5: <bevy_ecs::system::function_system::FunctionSystem<In,Out,Param,Marker,F> as bevy_ecs::system::system::System>::initialize
   6: <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run
   7: bevy_ecs::schedule::Schedule::run_once
   8: bevy_app::app::App::update
   9: bevy_winit::winit_runner_with::{{closure}}
  10: winit::platform_impl::platform::x11::EventLoop<T>::run_return
  11: winit::platform_impl::platform::x11::EventLoop<T>::run
  12: winit::platform_impl::platform::EventLoop<T>::run
  13: winit::event_loop::EventLoop<T>::run
  14: bevy_winit::run
  15: bevy_winit::winit_runner_with
  16: core::ops::function::Fn::call
  17: bevy_app::app::App::run
  18: marking::main
```

Every other example works here.

**Comment by nicopap** [comment]
Congratulation! You found a bevy bug. I'm fairly certain the example worked at one point. I'll see what I can do.

**Comment by nicopap** [comment]
Definitively not a bevy bug. I'll provide a patch shortly.

**Comment by linkmauve** [comment]
Thanks! <3
